apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.global.workloadIdentities.api.clientId }}
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gmail-sa
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.global.workloadIdentities.gmail.clientId }}
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-sa
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.global.workloadIdentities.ai.clientId }}
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rule-engine-sa
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.global.workloadIdentities.ruleEngine.clientId }}
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meeting-sa
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.global.workloadIdentities.meeting.clientId }}
  labels:
    azure.workload.identity/use: "true"
