global:
  registry: acraeroinboxprod.azurecr.io
  imagePrefix: aeroinbox
  namespace: production
  environment: production
  tenantId: d8537334-bc24-4daf-95a8-bf4c9fb14394
  keyVaultName: kv-aeroinbox-prod-6dc1a9
  workloadIdentities:
    api:
      clientId: 3be8b000-da5b-4c42-ad18-ec30e3dd1fb5
    gmail:
      clientId: 9eed5421-f9de-4d8d-949a-7db28015c8e6
    ai:
      clientId: fe524b15-088f-44f5-ade0-d1cd3a6c16cc
    ruleEngine:
      clientId: 9fed4f03-f70c-4ccb-83b0-c56c7549bada
    meeting:
      clientId: 7f1b6039-b227-4bd0-81e8-6345b0ee4e4b

api-service:
  image:
    repository: acraeroinboxprod.azurecr.io/aeroinbox/api-service
    tag: latest
    pullPolicy: Always
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  serviceAccount:
    name: api-sa
  service:
    port: 8000

gmail-service:
  image:
    repository: acraeroinboxprod.azurecr.io/aeroinbox/gmail-service
    tag: latest
    pullPolicy: Always
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  serviceAccount:
    name: gmail-sa
  service:
    port: 8000

ai-service:
  image:
    repository: acraeroinboxprod.azurecr.io/aeroinbox/ai-service
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  serviceAccount:
    name: ai-sa
  service:
    port: 8000

rule-engine:
  image:
    repository: acraeroinboxprod.azurecr.io/aeroinbox/rule-engine
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  serviceAccount:
    name: rule-engine-sa
  service:
    port: 8000

meeting-service:
  image:
    repository: acraeroinboxprod.azurecr.io/aeroinbox/meeting-service
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  serviceAccount:
    name: meeting-sa
  service:
    port: 8000

frontend:
  image:
    repository: acraeroinboxprod.azurecr.io/aeroinbox/frontend
    tag: latest
    pullPolicy: Always
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    port: 80
