global:
  registry: acraeroinboxprod.azurecr.io
  imagePrefix: aeroinbox
  namespace: production
  environment: production
  tenantId: d8537334-bc24-4daf-95a8-bf4c9fb14394
  keyVaultName: kv-aeroinbox-prod-881f9a
  redisHost: redis-aeroinbox-prod.indonesiacentral.redis.azure.net
  workloadIdentities:
    api:
      clientId: 9a0c3b24-68e7-4a51-a481-5df236998cc0
    gmail:
      clientId: 18f1165b-a27b-4569-9a71-14a03ce8c0d3
    ai:
      clientId: e5c5321e-19c0-4a0b-902b-8d5d52672743
    ruleEngine:
      clientId: df5b871c-bc82-4f09-9c3b-7211c4580d6e
    meeting:
      clientId: ca59e226-82f7-44b5-88a4-92635e4681f8

api-service:
  image:
    repository: acraeroinboxprod.azurecr.io/aeroinbox/api-service
    tag: latest
    pullPolicy: Always
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  serviceAccount:
    name: api-sa
  service:
    port: 8000

gmail-service:
  image:
    repository: acraeroinboxprod.azurecr.io/aeroinbox/gmail-service
    tag: latest
    pullPolicy: Always
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  serviceAccount:
    name: gmail-sa
  service:
    port: 8000

ai-service:
  image:
    repository: acraeroinboxprod.azurecr.io/aeroinbox/ai-service
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  serviceAccount:
    name: ai-sa
  service:
    port: 8000

rule-engine:
  image:
    repository: acraeroinboxprod.azurecr.io/aeroinbox/rule-engine
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  serviceAccount:
    name: rule-engine-sa
  service:
    port: 8000

meeting-service:
  image:
    repository: acraeroinboxprod.azurecr.io/aeroinbox/meeting-service
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  serviceAccount:
    name: meeting-sa
  service:
    port: 8000

frontend:
  image:
    repository: acraeroinboxprod.azurecr.io/aeroinbox/frontend
    tag: latest
    pullPolicy: Always
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  service:
    port: 80
