image:
  repository: ""
  tag: latest
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  path: /
  port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  path: /
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: /metrics
  prometheus.io/port: "3000"
