apiVersion: v1
kind: ConfigMap
metadata:
  name: aeroinbox-config
  namespace: aeroinbox
data:
  REDIS_HOST: redis-aeroinbox-prod.redis.cache.windows.net
  REDIS_PORT: "10000"
  REDIS_SSL: "true"
  SERVICE_BUS_NAMESPACE: sb-aeroinbox-prod.servicebus.windows.net
  SERVICE_BUS_QUEUE: meeting-reminders
  POSTGRES_PORT: "5432"
  AZURE_TENANT_ID: ea3249a3-251c-42d6-96a8-15bb78609c9f
  KEYVAULT_NAME: kv-aeroinbox-prod
  APPINSIGHTS_ENABLED: "true"
  LOG_LEVEL: INFO
  ENVIRONMENT: production
