apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aeroinbox-secret-provider
  namespace: aeroinbox
spec:
  provider: azure
  parameters:
    keyvaultName: kv-aeroinbox-prod-a2ea18
    tenantId: ea3249a3-251c-42d6-96a8-15bb78609c9f
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "1a19d0e6-48f7-4c06-9602-d1bb3c48e503"
    objects: |
      array:
        - |
          objectName: redis-access-key
          objectType: secret
        - |
          objectName: jwt-secret
          objectType: secret
        - |
          objectName: encryption-key
          objectType: secret
        - |
          objectName: postgres-host
          objectType: secret
        - |
          objectName: postgres-db-name
          objectType: secret
        - |
          objectName: postgres-admin-username
          objectType: secret
        - |
          objectName: application-insights-connection-string
          objectType: secret
        - |
          objectName: google-client-id
          objectType: secret
        - |
          objectName: google-client-secret
          objectType: secret
        - |
          objectName: azure-openai-api-key
          objectType: secret
