apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: aeroinbox
  annotations:
    azure.workload.identity/client-id: 5f138b29-32bf-49af-9460-0a70f0f03a5a
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gmail-sa
  namespace: aeroinbox
  annotations:
    azure.workload.identity/client-id: 773604a5-ec45-4e43-856d-866d29d2431e
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-sa
  namespace: aeroinbox
  annotations:
    azure.workload.identity/client-id: 75b81433-0bb0-44fa-ac85-164ba788156b
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rule-engine-sa
  namespace: aeroinbox
  annotations:
    azure.workload.identity/client-id: 326f5f81-feb5-42f0-b0e9-3666a0081ab9
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meeting-sa
  namespace: aeroinbox
  annotations:
    azure.workload.identity/client-id: d9194bc3-51b7-43f4-b7d3-711f1869c075
  labels:
    azure.workload.identity/use: "true"
