apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: aeroinbox
  annotations:
    azure.workload.identity/client-id: 1a19d0e6-48f7-4c06-9602-d1bb3c48e503
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gmail-sa
  namespace: aeroinbox
  annotations:
    azure.workload.identity/client-id: 94821263-29b7-4980-913c-c03080ef1257
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-sa
  namespace: aeroinbox
  annotations:
    azure.workload.identity/client-id: 251a81e6-963b-4d0f-929b-dbb938e95980
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rule-engine-sa
  namespace: aeroinbox
  annotations:
    azure.workload.identity/client-id: a90c9878-3410-4b9c-ab30-164dd6bb5f1f
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: meeting-sa
  namespace: aeroinbox
  annotations:
    azure.workload.identity/client-id: 5884d0d5-8707-43da-a4cc-38101d1e83aa
  labels:
    azure.workload.identity/use: "true"
