apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-auth
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: aeroinbox
    app.kubernetes.io/managed-by: Helm
spec:
  secretTargetRef:
  - parameter: connection
    name: meeting-service-secrets
    key: SERVICE_BUS_CONNECTION_STRING
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-scaler
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/part-of: aeroinbox
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-{{ .Chart.Name }}
  minReplicaCount: {{ .Values.autoscaling.minReplicas | default 1 }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas | default 2 }}
  triggers:
  - type: azure-servicebus
    metadata:
      queueName: meeting-reminders
      messageCount: "5"
    authenticationRef:
      name: {{ .Release.Name }}-{{ .Chart.Name }}-auth
