api-service:
  replicaCount: 1
  resources:
    limits:
      cpu: 250m
      memory: 256Mi

gmail-service:
  replicaCount: 1
  resources:
    limits:
      cpu: 250m
      memory: 256Mi

ai-service:
  replicaCount: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi

rule-engine:
  replicaCount: 1
  resources:
    limits:
      cpu: 250m
      memory: 256Mi

meeting-service:
  replicaCount: 1
  resources:
    limits:
      cpu: 250m
      memory: 256Mi

frontend:
  replicaCount: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
